### ISSUE TITLE
Transaction outputs should indicate if unspent or spending tx

### ISSUE THREAD

**Issue by chappjc** [dcrdata/dcrdata#110]

**Comment by raedah** [comment]
I imagine this could be done with a Spent column that indicates Yes or No.

**Comment by chappjc** [comment]
On Insight, the outputs have either a green (U) indicating unspent, or a ">" that is a link to the transaction that spends it.

**Comment by raedah** [comment]
Looks like what insight does is link to the address, and from the address page it is shown if it is spent or not. So lets show on the TX page if it is spent, and show on the Address page if its incoming or outgoing. These can just be put in a column for now, and we can change visual indicators once we are settled on the layout and move to design.

**Comment by chappjc** [comment]
For reference, here's Insight's display of spend outputs with a ">" that links to the spending tx:

![image](https://user-images.githubusercontent.com/9373513/30457067-e537f0ec-995a-11e7-870e-204a442c3042.png)

And unspent, with a green "U" that takes you nowhere, of course:

![image](https://user-images.githubusercontent.com/9373513/30457128-1fc2679c-995b-11e7-8920-b5bd01e5fc96.png)

**Comment by raedah** [comment]
Ah, never noticed that before. Insight has a few 'hidden' features. Will work on UI to make these things accessible.

**Comment by RogueElement** [comment]
I feel like there should be tool tips to give a bit of info on a lot of things.

**Comment by chappjc** [comment]
For now, just showing unspent if unspent is enough.  I'm going to make a new issue to create v2 of our database, with the ability to query for spent status, etc.

**Comment by chappjc** [comment]
@RogueElement I know you looked checking spent status some.  Was there a branch you were working on for this?

**Comment by RogueElement** [comment]
No, didn't actually have anything to code just theory, seemed like looking for the spending scriptsig that matches the spent scriptpubkey would work but that seem super inefficient so I just kept on looking.

**Comment by chappjc** [comment]
Yeah, we're gonna have to skip the link to spending tx for now.  Just showing spend/unspent status is enough for now.

**Comment by chappjc** [comment]
Addressed by @RogueElement in PR https://github.com/dcrdata/dcrdata/pull/231 (merged) and @chappjc in PR https://github.com/dcrdata/dcrdata/pull/209 (ready for review and merge)
