### ISSUE TITLE
Unconfirmed transactions need work in explorer

### ISSUE THREAD

**Issue by chappjc** [dcrdata/dcrdata#112]
This may be a bug in `getrawtransaction`, but anyway...

Take the following transaction view:

![image](https://user-images.githubusercontent.com/9373513/30090357-aadc8cea-9267-11e7-989e-74c5e4ff9621.png)

Issues:

- Except possibly for the tx id, all input values are bogus (e.g. value of -0.0000001)
- Transaction time say unix time 0, so this should be empty instead.
- Included in block says 0, but this isn't in the genesis block, it has yet to be mined.
- Need copy text icon on all hashes and addresses

**Comment by raedah** [comment]
Created separate issue for last item, 
https://github.com/dcrdata/dcrdata/issues/127

**Comment by raedah** [comment]
This looks fixed in https://github.com/dcrdata/dcrdata/pull/128
