### ISSUE TITLE
Wrong value inputs

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#116]
80debfca5171c2285f35490700fc35e399a15aef126d1948c2ad1756687a8389
-0.00000001 DCR

**Comment by RogueElement** [comment]
Yeah I don't know what happened there but some transactions seem to show the value -0.00000001 DCR for I while before reverting to the normal value, still trying to figure out why that is, maybe something with confirmations?

**Comment by chappjc** [comment]
Yes this is tx in mempool (unconfirmed).  See https://github.com/dcrdata/dcrdata/issues/112

**Comment by raedah** [comment]
This looks fixed in https://github.com/dcrdata/dcrdata/pull/128 , reopen if not.
