### ISSUE TITLE
Template enhancement roundup

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#118]
**Below items completed by @McEdward in https://github.com/dcrdata/dcrdata/pull/194**

Address template is showing invalid date Jan 1 00:00:00 1970 on unconfirmed transactions.

Transaction view with a Vote Reward should say Created for the block instead of N/A.

In Address on transaction template should be a link. **previously done**

On block and transaction templates, move Age field onto the same line as date.
Time (UTC) | 9/14/17 21:09:19 (4m 13s ago)

**Completed by @gozart1 in https://github.com/dcrdata/dcrdata/pull/185**

On the Block page, magic so that Total Value column so that the decimal points are always stacked ... and the 'DCR'. Same thing for the Size column with the B. Being right justified with other items, but left justified within the column.

**Below items are completed by @gozart1 in https://github.com/dcrdata/dcrdata/pull/150**

Need restyling on new search not found page.

Reduce the amount of surrounding white space on the tables so that more rows are shown. Depending on how much more data can be reasonably shown, default row count may be adjusted.

Pagination on blocks page, white space surrounding Older and Newer should be fixed, and font size needs to be worked with. Also, the Newer button is initially hidden, and the rest of the page shifts down when it appears. The page should not shift, so we should find a way to leave enough space at the top or can include the text 'Head of Chain' or 'Top' which is then replaced by the Newer link.

**Below items are completed by @gozart1 in https://github.com/dcrdata/dcrdata/pull/128**

Change default number of blocks listed on Blocks page to 12. (its one hour)

Reorder header
From:  Home   GitHub  API   Status  Explore
To:  Home  Explore  Status  API  Github
(or move items to footer)

On the Blocks and Address pages, from the Time column remove the repetitive +0000 UTC from each item, and change the column title to Time (UTC)

On the blocks page
Instead of Voters | Fresh Stake | Transactions
Use Votes, Tickets, Revocations, Transactions

Change pagination buttons from Previous Blocks Next Blocks, to  Older  Newer

Currently all html titles for pages are 'dcrdata web'
I suggest the title should say 
'Decred Blocks'
'Decred Transaction cc50e968f87476342e9...'   (truncated to 20 chars)
'Decred Address DsarUwfqxgrTryZbTDegCQ6ffm5CybmtSBv'
'Decred Block 166274'

Front page text can be simplified.
"Number of Tickets in Mempool (queued for mining):" -> "Tickets in Mempool:"
"Number of Tickets Mined in Last Block: "  -> "Tickets in Latest Block:"

**Comment by gozart1** [comment]
Great suggestions! I edited your comment into a task list, maybe we can explore a workflow around these for tracking sub-issue level stuff.

Here's a PR that relates to navigation reorganization https://github.com/dcrdata/dcrdata/pull/125

**Comment by raedah** [comment]
@gozart Most of the items on this are done, the remaining I think are yours.
