### ISSUE TITLE
Generated (coinbase) transactions are not showing in Address view

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#120]
f76d7edf77c4e2f490f46d9224c8966b91cc415b408eb9762
is not showing in the block view.

Address view 
Dsd1TDQw6idPfqnipC6Ww26TbgeBPkJzyR8
example 3f32fb5d191388b
see 00000... txid on 828ecf827711cb13df982e940a14153a7dd95be1b5bbb707bb7c453c9b115daf

**Below is completed in https://github.com/dcrdata/dcrdata/pull/128**
Also, they should be labeled.
00002f646372642f looks like it is Generated Coinbase
0000000000000000000000000000000000000000000000000000000000000000 looks like Vote Reward

**Comment by raedah** [comment]
This appears to be an upstream issue.

**Comment by chappjc** [comment]
I don't understand.  The address view generally seems to show both coinbase and stakebase transactions.  What isf76d7edf77c4e2f490f46d9224c8966b91cc415b408eb9762?

**Comment by raedah** [comment]
I am no longer able to reproduce this.
