### ISSUE TITLE
Top of an address page shows summary

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#121]
Transactions:
Total Received:
Current Balance:  or  'sum of unspent outputs (UTXOs)'
Unconfirmed:

We have a fixed limit of tx being displayed currently. If the # of transactions is less then the max, then display the sums. If we are hitting it we should not show the sums which would be incomplete, but do show a warned that all transactions are not being displayed below.

**Comment by raedah** [comment]
dup https://github.com/dcrdata/dcrdata/issues/131

**Comment by chappjc** [comment]
Needs aux/auxiliary DB (DB v2) to be built out first.  Namely, it needs address queries.

**Comment by raedah** [comment]
We were able to get all of this functioning without problem, just limited to addresses that return less then 500 transactions. https://github.com/dcrdata/dcrdata/compare/master...McEdward:summay_at_the_top_of_the_address_page

Just working out the dcrutil.Amount issue for the templates is left.  Looks like .ToUnit(-8) does the trick to return satoshis.
