### ISSUE TITLE
Give clear message instead of 422 InternalServiceError when tx not found

### ISSUE THREAD

**Issue by chappjc** [dcrdata/dcrdata#126]
For example, the first transaction in the genesis block: e7dfbceac9fccd6025c70a1dfa9302b3e7b5aa22fa51c98a69164ad403d60a2c

It's listed as a transaction on block 0, but it can't display it up because `getrawtransaction` fails (that's another issue as this is a special tx).  The web browser just shows:

    Internal Server Error

And the dcrdata logs show:

```
[ERR] DSQL: GetRawTransactionVerbose failed for: e7dfbceac9fccd6025c70a1dfa9302b3e7b5aa22fa51c98a69164ad403d60a2c
[ERR] JAPI: Unable to get transaction e7dfbceac9fccd6025c70a1dfa9302b3e7b5aa22fa51c98a69164ad403d60a2c
"GET http://dcrdata.ssgen.io/explorer/tx/e7dfbceac9fccd6025c70a1dfa9302b3e7b5aa22fa51c98a69164ad403d60a2c HTTP/1.1" from x.x.x.x - 500 22B in 1.316908ms
```

There should be a nice error message in the browser.  For instance, Insight via the search box has a transient text box that says "No matching records found!", while if you type in the URL for the missing transaction it redirects to the main explorer page showing latest blocks and a flash message that says "Transaction Not Found".

**Comment by raedah** [comment]
Completed in https://github.com/dcrdata/dcrdata/pull/128/
though template needs a restyling, tracking in https://github.com/dcrdata/dcrdata/issues/118
