### ISSUE TITLE
dcrwallet rpc integration

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#133]
Already started in branch https://github.com/dcrdata/dcrdata/tree/wallet

Add a config flag so that dcrwallet can be disabled, and dcrdata will continue working.
Wallet rpc needs to work with nodaemontls=0

Display a list of user transactions.
Display a list of tickets purchased. 
Possible fields, sstx id, date, price, vote date, reward, vote tx id

**Comment by chappjc** [comment]
Should this be it's own project, not Block Explorer?
