### ISSUE TITLE
Show transaction fees

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#138]
Transaction view should show Fee and Fee/size
Lets try and fit this on the transaction rows partial as well (and stake tx since they also have fees.)

For blocks, calculate mining fees collected in block (spent - sent).

**Comment by raedah** [comment]
I am seeing bad math on the fee calc, example 1280fabbc22201862d0d17ce41ba2429ca849a1851703da6d871d62e8e26d1b6

**Comment by raedah** [comment]
Looks like transaction fee is showing N/A on unconfirmed transactions, but we already know the fee before it gets confirmed.

**Comment by chappjc** [comment]
The unconfirmed issue goes back to this: https://github.com/dcrdata/dcrdata/issues/142

Regarding votes and fees, I'm pretty sure votes don't pay fees.

**Comment by chappjc** [comment]
closed by https://github.com/dcrdata/dcrdata/pull/202
