### ISSUE TITLE
For each tx input, show vout index in source transaction

### ISSUE THREAD

**Issue by chappjc** [dcrdata/dcrdata#140]
Perhaps replace the Sequence column, which is not very informative. (@RogueElement)

Instead of just the source transaction hash for each input, showing a prevout (txid:index) is more complete.

TODO (@chappjc): get the address of the pkScript of the referenced outpoint.

**Comment by chappjc** [comment]
In progress (input addresses)

**Comment by chappjc** [comment]
@raedah I think this addresses Issue https://github.com/dcrdata/dcrdata/issues/140.  Comments?

**Comment by raedah** [comment]
Works for me.
