### ISSUE TITLE
Show voting info on vote transactions

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#141]
Votes cast have associated data, looks like it needs to be decoded from the OP_RETURN, and then displayed.

Votes: https://github.com/decred/dcrd/blob/master/blockchain/chaingen/generator.go#L570-L627

activationNode := index.LookupNode(historicalSDiffActivationBlockHash);  
if activationNode != nil && node.height >= historicalSDiffActivationHeight && node.IsAncestor(activationNode) { /* new rules */ } else { /* old rules */ }

- [X] vote decoding
- [x] display on transaction page for votes
- [x] restyle display (@gozart1)

**Comment by chappjc** [comment]
I think this is addressed.  Was there additional info?

**Comment by raedah** [comment]
There may be an some side issues with the vote agendas and the activation heights for the voting periods, but the main thing is displaying the vote info in the user interface.

**Comment by chappjc** [comment]
Right, display.  :)  The API works, so everything is ready for the HTML template design part.  Not really where I know what to do though.

**Comment by chappjc** [comment]
@gozart1 I'm gonna get the data into the HTML template.  Can you do the tags to indicate the vote version and vote choices?

**Comment by chappjc** [comment]
Just an update.  PR https://github.com/dcrdata/dcrdata/pull/186 shows some of the vote info on the transaction page for a ssgen, but the way we display this data could perhaps be changed.

**Comment by chappjc** [comment]
closed by PR https://github.com/dcrdata/dcrdata/pull/186
