### ISSUE TITLE
Address view, transactions sort order reversed

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#143]
Should have newest first.

**Comment by chappjc** [comment]
`searchrawtransactions "address" (verbose=1 skip=0 count=100 vinextra=0 reverse=false ... )`

Need to flip to `reverse=true`

**Comment by chappjc** [comment]
bug in dcrrpcclient needs to be sorted out:  https://github.com/decred/dcrrpcclient/pull/89

**Comment by raedah** [comment]
if that fix isnt coming, could also reverse the list in go.

**Comment by chappjc** [comment]
For addresses like Dcur2 we don't actually have the whole list.  The reverse flag basically says to return the N of M newest tx first (N<=M), rather than the oldest.

**Comment by chappjc** [comment]
Ok, my PR https://github.com/decred/dcrrpcclient/pull/89 on dcrrpcclient was just merged so I can update deps and get this fixed.
