### ISSUE TITLE
Add latest blocks to home page

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#147]
Show first 6 blocks from the explorer, top center on home page, with a button underneath for 'more blocks' which goes to the explorer.

**Comment by chappjc** [comment]
Since https://github.com/dcrdata/dcrdata/issues/147 chops out so much info from the root explorer page, we I think it would be good to figure out what info will join the new page described in this issue, and make it a single PR.

**Comment by raedah** [comment]
All the same block info is going to be in the new explorer rows that are being added, so the only thing that is removed is the ticket fee info, because only the min fee is necessary now.

**Comment by chappjc** [comment]
Addressed by https://github.com/dcrdata/dcrdata/pull/163.  Can be closed I think
