### ISSUE TITLE
Transaction view should say what type of transaction it is

### ISSUE THREAD

**Issue by chappjc** [dcrdata/dcrdata#149]
- [x] Stake vs. regular, and if stake then what type - PR https://github.com/dcrdata/dcrdata/pull/164, but *still needs* <s>PR https://github.com/dcrdata/dcrdata/pull/167</s> stake type tags next to tx hash
- [x] Each output should say the type (stakegen, stakesubmission, sstxcommitment, sstxchange, etc.)

**Comment by raedah** [comment]
Related. Tickets have an OP_RETURN script for commitments (locked funds). Funds should show as locked and not sent to the receiving address until the state has changed.

Stake Commitments: https://github.com/decred/dcrd/blob/master/blockchain/chaingen/generator.go#L439-L482

**Comment by McEdward** [comment]
Would it be preferable if i added another column for that, or a single type column with something like this below  Vote/TxTypeSSGen?

**Comment by chappjc** [comment]
For each output type, it could be another column in the Out table

The type should be the all lowercase type.  Expand the details for this tx: https://mainnet.decred.org/tx/0893c4e266b2b4b076407314792a9a34eeaa73ea07d64c40e34ae07bf704666c

**Comment by chappjc** [comment]
@McEdward is on this too.

**Comment by chappjc** [comment]
Some tag-like solution is still needed for stake transactions I think: PR https://github.com/dcrdata/dcrdata/pull/167

**Comment by raedah** [comment]
Design for tags will be dealt with in a separate issue. @gozart1 is on it.

**Comment by chappjc** [comment]
closed by https://github.com/dcrdata/dcrdata/pull/184
