### ISSUE TITLE
Ticket commitment state

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#154]
Tickets have an OP_RETURN script for commitments ... locked funds. Funds should show as locked and not sent to the receiving address until the state has changed.

Stake Commitments: https://github.com/decred/dcrd/blob/master/blockchain/chaingen/generator.go#L439-L482

**Comment by chappjc** [comment]
Along the same line, a vote should show as locked funds until 256 confirms

**Comment by chappjc** [comment]
@raedah did @RogueElement hit everything in the PR just merge?
