### ISSUE TITLE
Link to corresponding vote/ticket for a ticket/vote

### ISSUE THREAD

**Issue by chappjc** [dcrdata/dcrdata#158]
In any view where a vote is shown, provide a link to the ticket purchase transaction.  Similarly, for a ticket, include a link to the vote or revocation if the ticket is spent.

**Comment by raedah** [comment]
Being able to link a ticket to a vote is dependent on being able to link a spent output to its spending transaction. Currently on hold in https://github.com/dcrdata/dcrdata/issues/110 and dependent on building the spent tx db, DB2 changes.

Linking a vote to the ticket is shown in the previous outpoint, so we could make a modification to the vote template to make this more obvious.

**Comment by chappjc** [comment]
Db2 is getting really close to being testable in dcrdata.  We'll be able to work on integrating it as a team really soon.  I expect we'll have a development branch though since I fully expect schema changes to occur and that would be painful for the public since it's around 2hr for a sync now

**Comment by chappjc** [comment]
Since db2 and the spending transaction support was implemented, all the necessary information should already be available in the html template data.  The ticket for a vote comes from the previous outpoint information of the vote's inputs.  The vote for a ticket, if one exists, comes from the "Spent" status if the ticket's stakesubmission output (output index 0) and the linked spending transaction.  Thus, it seems that all the necessary data is on the transaction page presently.
@McEdward ^

**Comment by chappjc** [comment]
To see how we go from vote to ticket, have a look at https://github.com/chappjc/votetime/blob/master/votetime.go

**Comment by raedah** [comment]
This appears to have been addressed by https://github.com/dcrdata/dcrdata/pull/293 , lets close if complete.
