### ISSUE TITLE
Add estimated net price to root page

### ISSUE THREAD

**Issue by RogueElement** [dcrdata/dcrdata#168]
As an extension of #163

**Comment by chappjc** [comment]
What do you mean by net price?  Like fiat value or market cap?

**Comment by RogueElement** [comment]
Market cap. Fiat would rely on elements outside of dcrdata and dcrd

**Comment by Henrychuks25** [comment]
Relying on other parameters could lead to unknown errors.

**Comment by raedah** [comment]
Will steer clear of the external dependency for now. Lots of local data to focus on. May open at a later time.
