### ISSUE TITLE
Block Subsidy is wrong on home page

### ISSUE THREAD

**Issue by gozart1** [dcrdata/dcrdata#173]
In the block subsidy table introduced in https://github.com/dcrdata/dcrdata/commit/64159cfb90215ddaa3bfd35981259afbf0b6c805
It looks like all the values are getting divided by 5, instead of just the PoS

**Comment by chappjc** [comment]
Ah that's right, setting voters to 1 affects the other components too. That RPC line will have to be for 5 voters, then divide the PoS by 5 (or just leave it depending on the semantics we are after).

**Comment by gozart1** [comment]
As a rule of thumb, could we keep the data being piped to the templates as raw as possible and leave the formatting to the template helper functions?

For example, CoinSupply is a string at the moment, it would be better if it could be some sort of numeric so we can run it through a humanize comma function.

**Comment by gozart1** [comment]
I think it would be fine to simply divide by 5 in the view layer for PoS per Ticket, since in a sense its just another way to look at the PoS subsidy.

**Comment by chappjc** [comment]
Closed by PR 175
