### ISSUE TITLE
Show minor vote info on Block Page

### ISSUE THREAD

**Issue by RogueElement** [dcrdata/dcrdata#187]
Maybe just a column to show the vote bits or columns to show the vote choice on LN or SdiffAlgo? Just something along those lines.

**Comment by raedah** [comment]
Can also be noted that we should be showing the basic vote info, which is the vote on if the previous block is accepted as valid.  Soon we will also have to be time boxing the additional votes, because their op_return identifiers will only be valid during their voting period and will be replaced with new voting info. Will be conditional upon the block height for a specific range that the voting takes place.

**Comment by chappjc** [comment]
Here's what we have now:

![image](https://user-images.githubusercontent.com/9373513/30725423-938c1fc6-9ef9-11e7-9b0a-1216aaa88ee5.png)

So we have a clear summary of the vote choices.  We do however lack an block validity indication, which is easily added.

The vote bits are there, as well as the vote version.  The vote version is used to fetch the data shown in the table out of the network's `chaincfg.Params`.  It is true that when dcrdata is rebuilt with a new version of `package chaincfg` that includes the next agenda and removes the previous, then this particular vote will no longer have any information displayed beyond version and bits.

**Comment by raedah** [comment]
Because of the new agendas, we will need to save the old the old agenda descriptions locally and display based on date. Unfortunately, dcrd wont have this historic data.

**Comment by chappjc** [comment]
Correct about storing agendas.  We had this issue for the official voting/hardfork demo site, and I implemented a database using a BoldDB ORM:  https://github.com/decred/hardforkdemo/pull/78
We can do something similar, or use the primary DB that's in the works.

**Comment by chappjc** [comment]
Note that it's not an issue yet as the v4 and v5 agendas are both still in the code: https://github.com/decred/dcrd/blob/master/chaincfg/params.go#L523-L606
