### ISSUE TITLE
DB v2 - New plugable blockchain database

### ISSUE THREAD

**Issue by chappjc** [dcrdata/dcrdata#189]
To support more complex operations, like identifying the spending tx for a STXO, and more efficient operations, as required for retrieving all transaction of a certain type or involving a certain address, there needs to be a proper database and a more thorough set of tables.

1. Deliverable:  `package dcrpg` - Postgres storage backend
2. Requirement:  New tables that (a) do not use height or hash as PK, but rather an auto inc, and (b) include all the data gleaned from getblock during scan, and possibly detailed transaction and address indexes too.
3. Goal:  Enable nuking reliance on most RPCs including:  `searchrawtransactions` and `getrawtransaction`.
4. Goal:  Obviate the need for the nasty caching hacks being tested for holding address search results.

Initial steps on the transition from sqlite to postgresql:

- [X] Database tables and queries needed to insert/select/update. (PR https://github.com/dcrdata/dcrdata/pull/209)
- [x] Hack it into supporting the vout spent/unspent issue on the transactions page.

For future:
- Make tests to prevent regressions in the next steps.
- Migrate all functionality required by the explorer (`ExplorerDataSource`) from using RPC calls to using the pg database (DBv2), except the ticket pool stuff that requires stakedb.
- Migrate all the functionality required by the API (`APIDataSource`) to DBv2, again except for stakedb parts.
- Decide if stakedb can be removed. Depends on ability to track ticket pool with alternate means.

**Comment by chappjc** [comment]
At this point, it makes sense for both @RogueElement and myself to tackle the remaining items.  Explorer v2 will have to go in first though.

**Comment by raedah** [comment]
As discussed on slack, the plan is to tie the development of the new db setup with the specific new features (git issues), such as 'identifying the spending tx for a STXO,' and 'retrieving all transaction involving a certain address'. This way we dont get into tearing out what is currently working well, and can prioritize by functionality created. Also that it should be feasible to keep a light weight mode mode that does not depend on postgres and keeps the existing rpc mode, though without the more advanced features that are yet to be implemented.

**Comment by chappjc** [comment]
Lightweight ("lite") mode implemented in PR https://github.com/dcrdata/dcrdata/pull/209

**Comment by chappjc** [comment]
closed by https://github.com/dcrdata/dcrdata/pull/209
