### ISSUE TITLE
Template roundup #2

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#195]
-Transaction view looks fine on chromium, but is broken on firefox.

-Block height is showing with commas on explorer page, and without on home page. I think we decided on without.

Transaction lists are showing erroneous amounts such as 342.64461200999995 
Need to make sure the float errors are fixed and **not covered up**.
https://github.com/dcrdata/dcrdata/pull/185/files#diff-cbc831f79556b345269731c1132a8412

On blocks list, size and age column data should be aligned on their right edge instead of the left edge.

**Comment by raedah** [comment]
will add these as a comment in gozarts open issue https://github.com/dcrdata/dcrdata/issues/200

**Comment by chappjc** [comment]
pretty sure this one is addressed.  @raedah ?
