### ISSUE TITLE
Design Overhaul

### ISSUE THREAD

**Issue by gozart1** [dcrdata/dcrdata#200]
Just wanted to share some screens from a layout & typography rework I've been exploring for the Transactions page. Your feedback is welcome.

My next step would be to implement something similar for block.tmpl so that things like the dcr total, fees and timestamp share layout location and styling between the block and tx views.

<img width="1128" alt="screen shot 2017-09-23 at 1 37 02 pm" src="https://user-images.githubusercontent.com/25571523/30776918-530ece78-a064-11e7-8635-c11f09060d5e.png">

<img width="693" alt="screen shot 2017-09-23 at 1 34 11 pm" src="https://user-images.githubusercontent.com/25571523/30776903-f5df1726-a063-11e7-8ffa-793da6bb67cc.png">

<img width="399" alt="screen shot 2017-09-23 at 1 33 57 pm" src="https://user-images.githubusercontent.com/25571523/30776902-f5c866f2-a063-11e7-915b-abdb2eb5c264.png">

**Comment by raedah** [comment]
Looks quite nice. One thought I have is shortening the previous outpoint with some javascript, and make it expand when clicked.   d25c...:0
I generally like the monospace font, but not a fan of the large spacing for the comma. I know we are using the monospace for the rest of the digits to line up here, so not sure how to get the best of both worlds. Maybe we dont need the commas on the value here at all. Commas make sense for coinsupply and difficult, so a rule of thumb could be just use them if dealing with things that are in millions. Not likely we will see a million dcr transaction.

**Comment by gozart1** [comment]
Thanks for comments, I've opened up a PR at https://github.com/dcrdata/dcrdata/pull/203 So we can continue convo there.

With the monospace + right align creating the nice line of decimals, commas aren't really necessary as you can quickly see how much DCR it is.

Source Sans Pro is more space efficient and readable so I think we should just use that in most cases.

How about this as a rule of thumb?
- Use Source Sans Pro as default, and use commas if it seems appropriate.
- For DCR values exclusively use the Inconsolata monospace font, no commas. 

I'm not sure about js shortening, the thought has crossed my mind as well, but adding something like this may get in the way of some users by adding an extra click, affect ctrl + f. Would also contribute to page load jank. I played around with a css only based approach using hover state and transforms but in the end decided less is more.

**Comment by linnutee** [comment]
Yep regarding typography: numbers and data strings have been with monospace in most past designs, normal bodycopy and titles with Source Sans Pro. 

Can look here for more reference:
https://www.notion.so/eeter/mainnet-decred-org-29098479211a49b0ae1fa3ec55b83537
https://www.notion.so/eeter/Design-Team-Delivery-Log-c743d9b25fda4de79c787783ac964014
