### ISSUE TITLE
More stats for front page

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#208]
Next ticket price estimate
Coins minted: 6,290,083 (29.9% mined so far of 21 million)
Transaction in Mempool: 4
Votes in Mempool: 2
PoS Poolsize: 40,824
Current PoS pool value: is 2,648,260 DCR (42.10 % of total available supply)
Average ticket price in pool: 64.87 DCR
Reward window progress: 4468 blocks left (15 days 11 hours)
show Developer Subsidy Funds available amount, with link to address page Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx

**Comment by raedah** [comment]
Provide link to genesis block
https://explorer.dcrdata.org/explorer/block/000000000000437482b6d47f82f374cde539440ddb108b0a76886f0d87d126b9

**Comment by chappjc** [comment]
That's actually the block after genesis, but I get what you mean.  This is genesis: https://explorer.dcrdata.org/explorer/block/298e5cc3d985bfe7f81dc135f360abe089edd4396b86d2de66b0cef42b21d980

This BTW contains an invalid transaction that we should probably hide or something.

**Comment by raedah** [comment]
Ahh ok, nevermind on that then. Block 1 is interesting because its the premine allocation tx. Maybe relevant information to show users somehow. As far as the invalid tx in the genesis, id special case tx id so instead of showing an error it explains to the user what happened there.

**Comment by chappjc** [comment]
Yes, I do think a premine information page would be pretty cool

**Comment by raedah** [comment]
Similiar to the Ticket Window Progress indicating bar, we can also add a Reward Adjustment Progress, which is block height / 6144.
