### ISSUE TITLE
Show block acceptance vote

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#217]
Currently vote info being displayed is for the agendas. The basic function of a vote transaction is to accept or reject the previous block produced by pow miners. This should be shown as the first item on the Vote Info.

**Comment by chappjc** [comment]
Yeah, not sure how this got lost.  I meant to try something like this:

![image](https://user-images.githubusercontent.com/9373513/31255775-803b01ae-a9e3-11e7-9ecc-16c0273cabfc.png)
