### ISSUE TITLE
Support multiple plugable backends, and light weight mode.

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#237]
Data retrieval layer should be abstracted from the rest of the code base. Currently dcrdata supports retrieving data from the dcrd RPC API. Postgresql support is incoming. Contributors in the future may likely want to add support for other databases. The user should be able to select in the dcrd.conf which data source they want to use. Data retrieval calls throughout the code base will use a generic data source object, with the specifics for retrieving from that data sources being defined in its their own file. The data source object should also have a property which specifies whether it should run in light weight mode. There are higher level calculations that will be done with postgresql that will not be supported in RPC mode, and when running in light weight mode some functionality in the explorer can be disabled.

**Comment by chappjc** [comment]
"lite" mode now exists in 1.0.0.

progress still needs to be made to ensure pluggability

**Comment by raedah** [comment]
Lite mode exists. As far as other modules, closing until the need for this arises.
