### ISSUE TITLE
case when no tickets are purchased in a block

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#245]
https://explorer.dcrdata.org/explorer/block/180000

Right now the header is by itself. 
We should add a row that says "No tickets mined this block."
Another possibility would be removing the ticket header entirely.

**Comment by chappjc** [comment]
Closed by https://github.com/dcrdata/dcrdata/issues/257

**Comment by raedah** [comment]
Reopening this, lets apply to votes as well, as illustrated here,
https://explorer.dcrdata.org/explorer/block/4095

**Comment by chappjc** [comment]
closed by https://github.com/dcrdata/dcrdata/pull/266
