### ISSUE TITLE
Searching for address with no transaction should not be error

### ISSUE THREAD

**Issue by chappjc** [dcrdata/dcrdata#255]
When searching for an address that has not had any transaction should still take you to the address page, not the /error page.

In fact, it would be nice if the address page would use a websocket to update when/if a transaction comes in for that address.

**Comment by RogueElement** [comment]
I could work this into #253

**Comment by chappjc** [comment]
@RogueElement Nah, let's do one page at a time.  Go ahead with 253 and we'll get to this.

About the error, I noticed that I somehow managed to pass a whitespace character all the way to the DecodeAddress part of the code.  We should strip all leading and trailing whitespaces from searches.

**Comment by McEdward** [comment]
@chappjc , please could you give an example of addresses that has not had any transaction.

**Comment by chappjc** [comment]
For example, you can use `getnewaddress` with to get a fresh address from your wallet.  The address itself is valid (would pass through the address validation functions since the network and checksum are OK), but there are no tx yet.  Ideally, we would respond with 0.0 DCR, no transactions, etc. but stay on the tx page so the websocket can update it when a relevant tx comes in.

**Comment by raedah** [comment]
More needs to be done here. Currently, searching still first takes the user to
https://explorer.dcrdata.org/search?search=ADDRESS
and then after at that URL they doing another search will redirect them to
https://explorer.dcrdata.org/address/ADDRESS
They should end up at the /address/ url the first time.
I also see the url alternating on repeated searches.

The other issue is that they are currently getting this returned
"Error: Something went wrong...
and it's not your fault, try refreshing... that usually fixes things"
They should instead end up at a the regular /address/ page which should be properly displaying 0 transactions. Make sure the template displays in the same format as our other pages for when zero items are being returned.
