### ISSUE TITLE
explorer: yyyy-mm-dd date format

### ISSUE THREAD

**Issue by xaur** [dcrdata/dcrdata#283]
Please show the dates as "yyyy-mm-dd hh:mm:ss".

This is almost ISO 8601, but I think space is more readable than "T" for humans.

The explorer already shows date-time in UTC and using 24-hour format, which is the right thing to target the whole world, but the mm/dd/yy date format is still very [US specific](https://en.wikipedia.org/wiki/Date_format_by_country).

**Comment by raedah** [comment]
okay with me

**Comment by xaur** [comment]
Sorry not sure I understand your question.

On the [main page](https://explorer.dcrdata.org/) the "UTC" label is present in column header. On the [block page](https://explorer.dcrdata.org/explorer/block/189179) the "(UTC)" prefix is in the "TIME" field, although I would move it to the label ("TIME UTC"). Same for [tx page](https://explorer.dcrdata.org/explorer/tx/73d8470b86a578ae7bdbc1ab42670971537fe16b6ecc01826a5b672d5e2f4aa0).

**Comment by chappjc** [comment]
Yeah, I agree that YYYY-MM-DD is less ambiguous.  I'm testing a diff here: https://github.com/dcrdata/dcrdata/pull/292

**Comment by xaur** [comment]
Is it deployed?

**Comment by raedah** [comment]
@xaur https://github.com/dcrdata/dcrdata/pull/292

**Comment by xaur** [comment]
Yeah, seen it merged but not live. All good now, thanks!
