### ISSUE TITLE
proposal: putting the vendor to git repo

### ISSUE THREAD

**Issue by detailyang** [dcrdata/dcrdata#289]
Hello.
Can we put the `vendor/` to the git repo (now it's in gitignore)?.

I know  putting the `vendor/` will bind us in the long term. But in china, `golang.org` or `google` will be blocked by [GFW](https://en.wikipedia.org/wiki/Great_Firewall). It will be difficult to install dependence on vps in china:(

**Comment by raedah** [comment]
As you said, it would 'bind us in the long term' so its not a good fix. I hope you find a better solution.

**Comment by detailyang** [comment]
@raedah okay. 
Consider it resolved
