### ISSUE TITLE
Add transaction types and allow querying via API

### ISSUE THREAD

**Issue by chappjc** [dcrdata/dcrdata#61]
As I stated on Slack, dcrdata was designed to return a lot of computed data -- things that may not be easy to get with just dcrctl and a node.

For example, the pool size and value at any past block.  That's tricky.   All of the ticket fee history was also of primary interest.

On the other hand, querying for transactions and such that are already available in many other ways, I have not prioritized.  **That said,** it does make sense to add more such things in the interest of having everything available in one spot.

One consideration is that I tried hard to minimize node RPC queries in favor of referencing pre-parsed data in a sql db or in memory data.  Whatever gets done, I don't want to create a way for the API to overload dcrd.

**Comment by chappjc** [comment]
First, this should also cover single outputs (amount, script) and outpoints (txid, index) as well as transactions.  Requirements:

- Looking up an outpoint should be a way to bring up an output, and vice versa.  They could also be combined in a different return type.
- Any address decoded from the output's `scriptPubKey` should be made available too.
- Ability to lookup the transaction that consumes an outpoint, if it exists.

Possible output API endpoint: `/api/tx/out/{txhash}/{index}` (or whatever makes it more resty 😛 )

Next, expanding on the transaction lookup feature, there are several possible API endpoints.  Here's a few,:

- Details of single transaction with amounts, scripts, etc..  e.g. `/api/tx/{txhash}`
- Reduced summary of tx inputs and outputs.  e.g. `/api/tx/{txhash}/io` (similarly for just outputs)
- List of spending transactions for each output.  e.g.  `/api/tx/{txhash}/spentby` for all outputs, or `/api/tx/{txhash}/spentby/{index}` for just one.
- Transactions in a block. e.g. `/api/block/{blockhash}/tx` or `/api/block/{blockhash}/tx/regular`, `/api/block/{blockhash}/tx/stake`

**Comment by fai04d** [comment]
That looks pretty good. I had a look at the docs for decoding a raw transaction but it didn't help very much. These are the sort of things I'd want to do:

- Given an address, get all transactions that used it.
- Given a block, get all inputs and outputs that occurred.
- Create a graph of all transactions using an address as a root. If the output of one transaction is the input of another, the database won't need to store links; they can be rebuilt dynamically.

It looks like what you've suggested above will be able to do that. I'll work from the database directly, so not too worried about API endpoints. Some of the stuff I want to do will overload an API anyway.

**Comment by chappjc** [comment]
@RogueElement I'll hammer this issue out pretty soon.  The websocket PR https://github.com/dcrdata/dcrdata/pull/51 and the caching PR https://github.com/dcrdata/dcrdata/pull/63 would be nice to get in first.  The WebSocket one is about ready, but the caching one has a couple more issues.  Anyway, pretty soon...

**Comment by RogueElement** [comment]
Okay, working on a web ui and want the transactions to be on the block page

**Comment by chappjc** [comment]
Much of this is already addressed by now, but we still need an address endpoint, and a few other things.
