### ISSUE TITLE
default to localhost http

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#78]
The default web server ip to listen on should not be public.
https://github.com/dcrdata/dcrdata/blob/master/sample-dcrdata.conf#L13
Could also use a better name like 'serverhost'

**Comment by chappjc** [comment]
That's a good point.  I should upload a sample nginx config to, since getting the websocket upgrade and RealIP parts correct can be tricky.

**Comment by chappjc** [comment]
Sample nginx config added in PR https://github.com/dcrdata/dcrdata/pull/88
