### ISSUE TITLE
Tag and Release at 0.7.x

### ISSUE THREAD

**Issue by chappjc** [dcrdata/dcrdata#89]
TODO:

- [x] merge [collectionQueue PR](https://github.com/dcrdata/dcrdata/pull/84)
- [x] merge [address endpoint PR](https://github.com/dcrdata/dcrdata/pull/93)
- [x] update README.md
- [x] bump ver in version.go
- [x] doc added types/funcs/etc.
- [x] sanity test all functionality
- [x] double check https://github.com/dcrdata/dcrdata/milestone/10
- [x] git tag
- [x] write GitHub release notes

Features for future release (**not** included in 0.7) are:

- [caching](https://github.com/dcrdata/dcrdata/pull/63) - this seems good, but there are some small remaining issues
- [dep migration from glide](https://github.com/dcrdata/dcrdata/pull/86)
- [wallet support](https://github.com/dcrdata/dcrdata/pull/68)
- block explorer

**Comment by chappjc** [comment]
I've assigned peeps just to draw attention.  No pressure to actually sink your time into this.  However, feedback regarding the testing portion would be greatly appreciated.

**Comment by RogueElement** [comment]
I'll get to work on updating the README.md and documenting the types/funcs, maybe add a few tests along the way

**Comment by chappjc** [comment]
@RogueElement Thanks for tackling the docs and README!

**Comment by RogueElement** [comment]
I would do the tests but I don't even know where to start since the program is not self-contained. Any pointers on the main functionality to test? I'm thinking testing the db connection, rpc connection and api endpoints

**Comment by chappjc** [comment]
@RogueElement unit tests will be great to have at some point, but for now I was just going through the API endpoints to make sure nothing was completely broken for reasonable inputs.

**Comment by chappjc** [comment]
Done!
