### ISSUE TITLE
Build Error: cannot use msgBlock (type *dcrutil.Block) as type *wire.MsgBlock in argument to dcrutil.NewBlock

### ISSUE THREAD

**Issue by RogueElement** [dcrdata/dcrdata#92]
Just pulled master and tried to build. Go this:
```
# github.com/dcrdata/dcrdata/rpcutils
rpcutils/rpcclient.go:219: cannot use msgBlock (type *dcrutil.Block) as type *wire.MsgBlock in argument to dcrutil.NewBlock
```
However, it didn't give an error for dcrsqlite/sync.go:336 which is the exact same thing

**Comment by chappjc** [comment]
I think this PR is hitting you: https://github.com/dcrdata/dcrdata/pull/80  If the instructions there fix the build error, you may close the issue.

**Comment by RogueElement** [comment]
Sorry to bother you, didn't see that

**Comment by chappjc** [comment]
No, no bother!  Things are moving very quickly on master right now, so it's easy to miss stuff like that.
